Update main.yaml 4.0.2

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -283,31 +283,31 @@ jobs:
           CSPM_URL: https://eu-1.api.cloudsploit.com
           TRIVY_RUN_AS_PLUGIN: "aqua"
 
-      - name: Manifest Generation
-        if: ${{ github.event_name != 'pull_request' }}
-        run: |
-          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum --check; then
-          echo "install.sh checksum failed"
-          exit 1
-          fi
-          BINDIR="." sh install.sh
-          rm install.sh install.sh.checksum
-          ./billy generate \
-            --access-token "${{ secrets.GH_PAT_PASSWORD }}" \
-            --aqua-key "${{ secrets.AQUA_KEY_EU }}" \
-            --aqua-secret "${{ secrets.AQUA_SECRET_EU }}" \
-            --cspm-url "https://eu-1.api.cloudsploit.com" \
-            --artifact-path "nishadali/aqua-test:${{ github.run_number }}" \
-            --debug
-        env:
-          AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
-          CSPM_URL: https://eu-1.api.cloudsploit.com
-          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
-          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
-          TRIVY_DB_REPOSITORY: "registry.aquasec.com/trivy-db:2"
-          TRIVY_JAVA_DB_REPOSITORY: "registry.aquasec.com/trivy-java-db:1"
-          TRIVY_CHECKS_BUNDLE_REPOSITORY: "registry.aquasec.com/trivy-checks:1"
+      # - name: Manifest Generation
+      #   if: ${{ github.event_name != 'pull_request' }}
+      #   run: |
+      #     export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+      #     curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+      #     curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+      #     if ! cat install.sh.checksum | sha256sum --check; then
+      #     echo "install.sh checksum failed"
+      #     exit 1
+      #     fi
+      #     BINDIR="." sh install.sh
+      #     rm install.sh install.sh.checksum
+      #     ./billy generate \
+      #       --access-token "${{ secrets.GH_PAT_PASSWORD }}" \
+      #       --aqua-key "${{ secrets.AQUA_KEY_EU }}" \
+      #       --aqua-secret "${{ secrets.AQUA_SECRET_EU }}" \
+      #       --cspm-url "https://eu-1.api.cloudsploit.com" \
+      #       --artifact-path "nishadali/aqua-test:${{ github.run_number }}" \
+      #       --debug
+      #   env:
+      #     AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
+      #     CSPM_URL: https://eu-1.api.cloudsploit.com
+      #     TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
+      #     TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
+      #     TRIVY_DB_REPOSITORY: "registry.aquasec.com/trivy-db:2"
+      #     TRIVY_JAVA_DB_REPOSITORY: "registry.aquasec.com/trivy-java-db:1"
+      #     TRIVY_CHECKS_BUNDLE_REPOSITORY: "registry.aquasec.com/trivy-checks:1"
 
